routes/web.php
<?php

use App\Http\Controllers\AreaController;
use App\Http\Controllers\Auth\SuperAuthController;
use App\Http\Controllers\BreifController;
use App\Http\Controllers\BridController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CenterController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DashbordController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\SuperController;
use App\Http\Controllers\VillageController;
use App\Http\Controllers\VisionController;
use App\Models\Area;
use App\Models\Super;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('cms/admin')->middleware('auth:super')->group(function () {

        Route::resource('vision', VisionController::class);
        Route::resource('village', VillageController::class)->middleware('auth:super');
        Route::resource('category',CategoryController::class)->middleware('auth:super');
        Route::resource('message',MessageController::class)->middleware('auth:super');
        Route::resource('breif',BreifController::class)->middleware('auth:super');
        Route::resource('area',AreaController::class)->middleware('auth:super');
        Route::resource('brid',BridController::class)->middleware('auth:super');
        Route::resource('super',SuperController::class)->middleware('auth:super');

        Route::resource('center',CenterController::class)->middleware('auth:super')->middleware('auth:super');
        Route::get('/',[DashbordController::class,'admin'])->name('admin.dashbord')->middleware('auth:super');
        Route::get('logout', [SuperAuthController::class,'logout'])->name('super.logout')->middleware('auth:super');

});

Route::prefix('cms/admin/')->namespace('Auth')->group(function () {

    Route::get('page/login', [SuperAuthController::class,'showLoginView'])->name('super.login.view');
    Route::post('login',  [SuperAuthController::class,'login'])->name('super.login.store');
    Route::get('blocked', [SuperAuthController::class,'blocked'])->name('super.blocked');

    // Route::get('forgot-password', 'AdminAuthController@showForgetPassword')->name('cms.admin.forgot_password_view');
    // Route::post('forgot-password', 'AdminAuthController@requestNewPassword')->name('cms.admin.forgot_password');
});

Route::get('/test', function () {
    App::setLocale('en');
    dd(App::getLocale());
});

app/Models/Super.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Super extends Authenticatable
{
    use HasFactory;
}

app/Http/Controllers/SuperController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateSuper;
use App\Models\Super;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Hash;

class SuperController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $super= new Super();
        // $super->name="gggg";
        // $super->email="h1@gmail.com";
        // $super->password=Hash::make('123456');
        // $super->save();
        // dd(4554);
        $supers=Super::all();
        return view('cms.admin.supers.index',['supers'=>$supers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cms.admin.supers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateSuper $request)
    {
        //
        $super=new Super();
        $super->name=$request->get('name');
        $super->email=$request->get('email');
        $super->password=Hash::make(($request->get('password')));
        $super->status = $request->get('status') == 'on' ? 'Active' : 'InActive';
           if ($request->hasFile('image')) {
            $imagefile = $request->file('image');
            $imagename = time() . 'center' . 'Super' . ' ' . ' ' . $imagefile->getClientOriginalName();

            $imagefile->move('images/supers', $imagename);
            $super->image = $imagename;
        }

              $save=$super->save();

            if ($save) {


                SuccessError::Success('تم الإنشاء بنجاح');
                return redirect()->back();





        }


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Super  $super
     * @return \Illuminate\Http\Response
     */
    public function show(Super $super)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Super  $super
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('cms.admin.supers.edit',['super'=>Super::find($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Super  $super
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {

         $request->request->add(['id' => $id]);
        $request->validate([
            'name'=>'required',
            'email'=>'required|email|unique:supers,email,' .$id,
            'image'=>'image',
        ],[

        'name.required'=>'الإسم فارغ',
         'email.required'=>'الإيميل فارغ',
         'email.email'=>'الرجاء التأكد من الإيميل',
         'email.unique'=>'الإيميل مُكرر',
         'image.image'=>'الرجاء رفع صورة'
        ]
    );


      $super=Super::find($id);
        $super->name=$request->get('name');
        $super->email=$request->get('email');
        $super->password=Hash::make(($request->get('password')));
        $super->status = $request->get('status') == 'on' ? 'Active' : 'InActive';
           if ($request->hasFile('image')) {
            $imagefile = $request->file('image');
            $imagename = time() . 'center' . 'Super' . ' ' . ' ' . $imagefile->getClientOriginalName();

            $imagefile->move('images/supers', $imagename);
            $super->image = $imagename;
        }

              $save=$super->save();

            if ($save) {


                SuccessError::Success('تم التعديل بنجاح');
                return redirect()->back();




        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Super  $super
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return 1;
        //
    }
}

resources/views/cms/admin/supers/create.blade.php
@extends('cms.admin.parent')
@section('lang')
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item pt-2 pb-2" href="{{ route(
                                            request()->route()->getName(),
                                            ['en', 1],
                                        ) }}"><img src="{{ asset('cms/assets/images/flag/us.svg') }} "
                class="w20 mr-2 rounded-circle"> US English</a>


        <a class="dropdown-item pt-2 pb-2" href="{{ route(
                                            request()->route()->getName(),
                                            ['ar', 1],
                                        ) }}"><img src="{{ asset('cms/assets/images/flag/arabia.svg') }} "
                class="w20 mr-2 rounded-circle"> العربية</a>

    </div>
@endsection
@section('content')
    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">

                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{route('admin.dashbord')}}" style="font-size: 20px">الرئيسية</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('super.index') }}"
                                style="font-size: 20px">الأدمن</a></li>
                                <li class="breadcrumb-item active" aria-current="page" style="font-size: 20px">أدمن جديد
                                </li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                        {{-- <a
                            href="https://themeforest.net/item/oculux-bootstrap-4x-admin-dashboard-clean-modern-ui-kit/23091507"
                            class="btn btn-sm btn-success" title="Themeforest"><i class="icon-basket"></i> Buy Now</a>
                        --}}
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="body">
                            <form method="POST" action="{{ route('super.store') }}" enctype="multipart/form-data">


                                @if ($errors->any())
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                    </div>
                                @endif
                                @if (session()->has('message'))
                                    <div class="alert {{ session()->get('status') }} alert-dismissible fade show"
                                        role="alert">
                                        <span> {{ session()->get('message') }}</span>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endif
                                @csrf
                                <div class="form-group row">
                                    <div class="col-md-10 col-sm-10">

                                        <div class="form-group">
                                        <label style="font-size: 20px">الإسم</label>
                                            <input type="text" class="form-control" value="{{ old('name') }}"
                                                style="font-size: 20px" name="name" >


                                        </div>
                                                              <div class="form-group">
                                                              <label style="font-size: 20px">الإيميل</label>
                                            <input type="text" class="form-control" value="{{ old('email') }}"
                                                style="font-size: 20px" name="email">


                                        </div>
                                                              <div class="form-group">
                                                              <label style="font-size: 20px">كلمة السر</label>
                                            <input type="password" class="form-control"
                                                style="font-size: 20px" name="password" >


                                        </div>
                                                              <div class="form-group">
                                            <label style="font-size: 20px">تأكيد كلمة السر</label>
                                            <input type="password" class="form-control"
                                                style="font-size: 20px" name="confirm" >


                                        </div>


                                        <div class="row clearfix">
                                            <div class="col-lg-12">
                                                <label style="font-size: 20px"> الصورة </label>
                                                <input type="file" width="590px" height="390px" class="dropify"
                                                    name="image">
                                            </div>

                                        </div>



                                        <div class="form-group">
                                            <label style="font-size: 20px">الحالة</label>
                                            <div class="custom-control custom-switch">
                                                <input type="checkbox" class="custom-control-input" name="status"
                                                    id="status" @if (old('status') == 'on')
                                                checked @endif>
                                                <label class="custom-control-label" style="font-size: 20px"
                                                    for="status">مُفعلة</label>

                                            </div>
                                        </div>


                                    </div>
                                </div>
                                <div>
                                    <button style="font-size: 20px" class="btn btn-sm btn-primary" type="submit"> حفظ
                                    </button>


                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>

    </script>

@endsection

resources/views/cms/admin/supers/edit.blade.php
@extends('cms.admin.parent')
@section('lang')
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item pt-2 pb-2" href="{{ route(
                                            request()->route()->getName(),
                                            ['en', $super->id],
                                        ) }}"><img src="{{ asset('cms/assets/images/flag/us.svg') }} "
                class="w20 mr-2 rounded-circle"> US English</a>


        <a class="dropdown-item pt-2 pb-2" href="{{ route(
                                            request()->route()->getName(),
                                            ['ar', $super->id],
                                        ) }}"><img src="{{ asset('cms/assets/images/flag/arabia.svg') }} "
                class="w20 mr-2 rounded-circle"> العربية</a>

    </div>
@endsection
@section('content')
    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">

                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ route('admin.dashbord') }}"
                                style="font-size: 20px">الرئيسية</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('super.index') }}"
                                style="font-size: 20px">الأدمن</a></li>
                                <li class="breadcrumb-item active" aria-current="page" style="font-size: 20px">تعديل
                                </li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                        {{-- <a
                            href="https://themeforest.net/item/oculux-bootstrap-4x-admin-dashboard-clean-modern-ui-kit/23091507"
                            class="btn btn-sm btn-success" title="Themeforest"><i class="icon-basket"></i> Buy Now</a>
                        --}}
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="body">
                            <form method="POST" action="{{ route('super.update',[$super->id]) }}" enctype="multipart/form-data">
                                @method("PUT")

                                @if ($errors->any())
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                    </div>
                                @endif
                                @if (session()->has('message'))
                                    <div class="alert {{ session()->get('status') }} alert-dismissible fade show"
                                        role="alert">
                                        <span> {{ session()->get('message') }}</span>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endif
                                @csrf
                                <div class="form-group row">
                                    <div class="col-md-10 col-sm-10">

                                        <div class="form-group">
                                        <label style="font-size: 20px">الإسم</label>
                                            <input type="text" class="form-control" value="{{ $super->name }}"
                                                style="font-size: 20px" name="name" >


                                        </div>
                                                              <div class="form-group">
                                                              <label style="font-size: 20px">الإيميل</label>
                                            <input type="text" class="form-control" value="{{ $super->email }}"
                                                style="font-size: 20px" name="email">


                                        </div>




                                        <div class="row clearfix">
                                            <div class="col-lg-12">
                                                <label style="font-size: 20px"> الصورة </label>
                                                <input type="file" width="590px" height="390px" class="dropify"
                                            data-default-file="{{ url('images/supers/' . $super->image) }}"        name="image">
                                            </div>

                                        </div>



                                        <div class="form-group">
                                            <label style="font-size: 20px">الحالة</label>
                                            <div class="custom-control custom-switch">
                                                <input type="checkbox" class="custom-control-input" name="status"
                                                    id="status" @if ($super->status == 'Active')
                                                checked @endif>
                                                <label class="custom-control-label" style="font-size: 20px"
                                                    for="status">مُفعلة</label>

                                            </div>
                                        </div>


                                    </div>
                                </div>
                                <div>
                                    <button style="font-size: 20px" class="btn btn-sm btn-primary" type="submit"> تعديل
                                    </button>


                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>

    </script>

@endsection

resources/views/cms/admin/supers/index.blade.php
@extends('cms.admin.parent')
@section('lang')
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item pt-2 pb-2" href="{{ route(
                                            request()->route()->getName(),
                                            ['en', 1],
                                        ) }}"><img src="{{ asset('cms/assets/images/flag/us.svg') }} "
                class="w20 mr-2 rounded-circle"> US English</a>


        <a class="dropdown-item pt-2 pb-2" href="{{ route(
                                            request()->route()->getName(),
                                            ['ar', 1],
                                        ) }}"><img src="{{ asset('cms/assets/images/flag/arabia.svg') }} "
                class="w20 mr-2 rounded-circle"> العربية</a>

    </div>
@endsection

@section('content')

    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ route('admin.dashbord') }}"
                                        style="font-size: 20px">الرئيسية</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('super.create') }}"
                                        style="font-size: 20px">أدمن جديد</a></li>
                                <li class="breadcrumb-item " style="font-size: 20px" aria-current="page">
                                   الأدمن
                                </li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>

            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="header">
                            <h2 style="font-size: 20px">{{ __('parent.super') }}</h2>

                        </div>
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example dataTable table-custom spacing5 mb-0">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th style="font-size: 17px">الصورة</th>
                                        <th style="font-size: 17px"> الإسم</th>
                                        <th style="font-size: 17px">الإيميل </th>
                                        {{-- <th style="font-size: 17px">{{ __('general.show') }} </th> --}}
                                        <th style="font-size: 17px">الحالة</th>
                                        <th style="font-size: 17px">تاريخ الإنشاء</th>
                                        <th style="font-size: 17px">الإعدادات</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <span hidden>{{ $i = 0 }}</span>
                                    @foreach ($supers as $item)
                                        <span hidden>{{ $i++ }}</span>

                                        <tr>
                                            <td>{{ $i }}</td>
                                            <td class="w60">
                                                <img src="{{ url('images/supers/' . $item->image) }}"
                                                    data-toggle="tooltip" data-placement="top" title="{{ $item->name }}"
                                                    alt="Avatar" class="w35 h35 rounded">
                                            </td>



                                                <td><span style="font-size: 17px">{{ $item->name }}</span></td>
                                                  <td><span style="font-size: 17px">{{ $item->email }}</span></td>



                                            {{-- <td>
                                                <a class="btn btn-info btn-sm"
                                                    href="{{ route('super.show', [app()->getLocale(), $item->id]) }}">
                                                    <i class="icon-note">
                                                    </i>
                                                    {{ __('general.show') }}
                                                </a>
                                                <span class="badge badge-dark"></span>
                                            </td> --}}
                                            <td>
                                                @if ($item->status == 'Active')
                                                    <span style="font-size: 17px"
                                                        class="badge badge-success">فعّال</span>
                                                @else
                                                    <span style="font-size: 17px"
                                                        class="badge badge-danger">متوقفة</span>
                                                @endif

                                            </td>
                                            <td><span
                                                    style="font-size: 17px">{{ $item->created_at->format('Y.m.d') }}</span>
                                            </td>

                                            <td>
                                                <a href="{{ route('super.edit',  $item->id) }}"
                                                    type="button" style="font-size: 20px" class="btn btn-sm btn-default"
                                                    title="تعديل"><i class="fa fa-edit"></i>
                                                    تعديل</a>
                                                <a onclick="confirmDelete(this, '{{ $item->id }}')" type="button"
                                                    style="font-size: 20px" class="btn btn-sm btn-default js-sweetalert"
                                                    title=" حذف" data-type="confirm"><i
                                                        class="fa fa-trash-o text-danger">
                                                       حذف </i></a>


                                            </td>




                                            {{-- <td>
                                                <a href="javascript:void(0);" class="btn btn-info btn-round">Interview</a>

                                            </td> --}}
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

@endsection
@section('script')
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script>
        function confirmDelete(app, id) {

            Swal.fire({
                title: 'هل انت متأكد من الحذف ؟',
                text: "لن تكون قادرا على استرجاعها",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'حذف',
                cancelButtonText: 'تراجع'
            }).then((result) => {
                if (result.value) {
                    deletecategory(app, id, )
                }
            })
        }

        function deletecategory(app, id) {
            axios.delete('/cms/admin/super/' + id)
                .then(function(response) {
                    // handle success (Status Code: 200)
                    console.log(response);
                    console.log(response.data);
                    showMessage(response.data);
                    app.closest('tr').remove();
                })
                .catch(function(error) {
                    // handle error (Status Code: 400)
                    console.log(error);
                    console.log(error.response.data);
                    showMessage(error.response.data);
                })
                .then(function() {
                    // always executed
                });
        }

        function showMessage(data) {
            Swal.fire({
                position: 'center',
                icon: data.icon,
                title: data.title,
                showConfirmButton: false,
                timer: 1500
            })
        }

    </script>

@endsection