routes/web.php
<?php

use App\Http\Controllers\AreaController;
use App\Http\Controllers\Auth\SuperAuthController;
use App\Http\Controllers\BreifController;
use App\Http\Controllers\BridController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CenterController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DashbordController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\SuperController;
use App\Http\Controllers\VillageController;
use App\Http\Controllers\VisionController;
use App\Models\Area;
use App\Models\Super;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('cms/admin')->middleware('auth:super')->group(function () {

        Route::resource('vision', VisionController::class);
        Route::resource('village', VillageController::class)->middleware('auth:super');
        Route::resource('category',CategoryController::class)->middleware('auth:super');
        Route::resource('message',MessageController::class)->middleware('auth:super');
        Route::resource('breif',BreifController::class)->middleware('auth:super');
        Route::resource('area',AreaController::class)->middleware('auth:super');
        Route::resource('brid',BridController::class)->middleware('auth:super');
        Route::resource('super',SuperController::class)->middleware('auth:super');

        Route::resource('center',CenterController::class)->middleware('auth:super')->middleware('auth:super');
        Route::get('/',[DashbordController::class,'admin'])->name('admin.dashbord')->middleware('auth:super');
        Route::get('logout', [SuperAuthController::class,'logout'])->name('super.logout')->middleware('auth:super');

});

Route::prefix('cms/admin/')->namespace('Auth')->group(function () {

    Route::get('page/login', [SuperAuthController::class,'showLoginView'])->name('super.login.view');
    Route::post('login',  [SuperAuthController::class,'login'])->name('super.login.store');
    Route::get('blocked', [SuperAuthController::class,'blocked'])->name('super.blocked');

    // Route::get('forgot-password', 'AdminAuthController@showForgetPassword')->name('cms.admin.forgot_password_view');
    // Route::post('forgot-password', 'AdminAuthController@requestNewPassword')->name('cms.admin.forgot_password');
});

Route::get('/test', function () {
    App::setLocale('en');
    dd(App::getLocale());
});

app/Models/Village.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Village extends Model
{
    use HasFactory;
}

app/Http/Controllers/VillageController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateVillage;
use App\Http\Requests\EditVillage;
use App\Models\Village;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;

class VillageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


        $villages=Village::all();
        return view('cms.admin.villages.index',['villages'=>$villages]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cms.admin.villages.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateVillage $request)
    {
        //
        // dd(45);
        $village=new Village();
        $village->nameen=$request->get('nameen');
  $village->namear=$request->get('namear');
           if ($request->hasFile('image')) {
            $imagefile = $request->file('image');
            $imagename = time() . 'center' . 'Village'. ' ' . ' ' .$imagefile->getClientOriginalName();

            $imagefile->move('images/villages', $imagename);
            $village->image = $imagename;
        }
        $village->descen=$request->get('descen');
           $village->descar=$request->get('descar');
        $village->status = $request->get('status') == 'on' ? 'Visible' : 'InVisible';

           $save=$village->save();
        if ($save) {



                SuccessError::Success('تم الإنشاء بنجاح');
                return redirect()->back();




        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Village  $village
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $village=Village::find($id);
        return view('cms.admin.villages.show',['village'=>$village]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Village  $village
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $village=Village::find($id);
        return view('cms.admin.villages.edit',['village'=>$village]);


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Village  $village
     * @return \Illuminate\Http\Response
     */
    public function update(EditVillage $request, $id)
    {
        //

           $village=Village::find($id);


           if ($request->hasFile('image')) {
            $imagefile = $request->file('image');
            $imagename = time() . 'center' . 'Village'. ' ' . ' ' .$imagefile->getClientOriginalName();

            $imagefile->move('images/villages', $imagename);
            $village->image = $imagename;
        }
        $village->descar=$request->get('descar');
        $village->descen=$request->get('descen');
        $village->namear=$request->get('namear');
        $village->nameen=$request->get('nameen');
        $village->status = $request->get('status') == 'on' ? 'Visible' : 'InVisible';

           $save=$village->save();
        if ($save) {



                SuccessError::Success('تم التعديل بنجاح');
                return redirect()->back();




        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Village  $village
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete = Village::destroy($id);

        if ($delete) {

             return response()->json(['icon' => 'success', 'title' => 'تم الحذف بنجاح  '], 200);






        }
    }
}

resources/views/cms/admin/villages/create.blade.php
@extends('cms.admin.parent')

@section('content')



    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ route('admin.dashbord') }}"
                                        style="font-size: 20px">الرئيسية</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('center.index') }}"
                                        style="font-size: 20px">المركز الإعلامي</a></li>
                                <li class="breadcrumb-item active" aria-current="page" style="font-size: 20px">
                                    القرى والبلدات
                                </li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                        {{-- <a
                            href="https://themeforest.net/item/oculux-bootstrap-4x-admin-dashboard-clean-modern-ui-kit/23091507"
                            class="btn btn-sm btn-success" title="Themeforest"><i class="icon-basket"></i> Buy Now</a>
                        --}}
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="body">
                            <form method="POST" action="{{ route('village.store') }}" enctype="multipart/form-data">


                                @if ($errors->any())
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                    </div>
                                @endif
                                @if (session()->has('message'))
                                    <div class="alert {{ session()->get('status') }} alert-dismissible fade show"
                                        role="alert">
                                        <span> {{ session()->get('message') }}</span>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endif
                                @csrf
                                <div class="form-group row">
                                    <div class="col-md-12 col-sm-10">

                                        <div class="form-group">
                                            <label style="font-size: 20px">اسم القرية -عربي </label>
                                            <input type="text" class="form-control" value="{{ old('namear') }}"
                                                style="font-size: 20px" name="namear">


                                        </div>
                                        <div class="form-group">
                                            <label style="font-size: 20px">اسم القرية - إنجليزي</label>
                                            <input type="text" class="form-control" value="{{ old('nameen') }}"
                                                style="font-size: 20px" name="nameen">


                                        </div>
                                        <div class="form-group">
                                            <label style="font-size: 20px">الوصف - عربي</label>

                                            <textarea name="descar" rows="10"
                                                class="form-control no-resize">{{ old('descar') }}</textarea>
                                        </div>
                                        <div class="form-group">
                                            <label style="font-size: 20px">الوصف - إنجليزي</label>

                                            <textarea name="descen" rows="10"
                                                class="form-control no-resize">{{ old('descen') }}</textarea>
                                        </div>



                                        <div class="row clearfix">
                                            <div class="col-lg-12">
                                                <label style="font-size: 20px">الصورة</label>
                                                <input type="file" width="590px" height="390px" class="dropify"
                                                    name="image">
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label style="font-size: 20px">الحالة</label>
                                            <div class="custom-control custom-switch">
                                                <input type="checkbox" class="custom-control-input" name="status"
                                                    id="status" @if (old('status') == 'on')
                                                checked @endif>
                                                <label class="custom-control-label" style="font-size: 20px"
                                                    for="status">التفعيل</label>

                                            </div>
                                        </div>




                                    </div>
                                </div>
                                <div>
                                    <button style="font-size: 20px" class="btn btn-sm btn-primary" type="submit">
                                        حفظ
                                    </button>


                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>

    </script>

@endsection

resources/views/cms/admin/villages/edit.blade.php
@extends('cms.admin.parent')

@section('content')



    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ route('admin.dashbord') }}"
                                        style="font-size: 20px">الرئيسية</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('village.index') }}"
                                        style="font-size: 20px">القرى والبلدات</a></li>
                                <li class="breadcrumb-item active" aria-current="page" style="font-size: 20px">
                                    تعديل
                                </li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                        {{-- <a
                            href="https://themeforest.net/item/oculux-bootstrap-4x-admin-dashboard-clean-modern-ui-kit/23091507"
                            class="btn btn-sm btn-success" title="Themeforest"><i class="icon-basket"></i> Buy Now</a>
                        --}}
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="body">
                            <form method="POST" action="{{ route('village.update', $village->id) }}"
                                enctype="multipart/form-data">
                                @method("PUT")

                                @if ($errors->any())
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                    </div>
                                @endif
                                @if (session()->has('message'))
                                    <div class="alert {{ session()->get('status') }} alert-dismissible fade show"
                                        role="alert">
                                        <span> {{ session()->get('message') }}</span>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endif
                                @csrf
                                <div class="form-group row">
                                    <div class="col-md-12 col-sm-10">

                                        <div class="form-group">
                                            <label style="font-size: 20px">اسم القرية - عربي</label>
                                            <input type="text" class="form-control" value="{{ $village->namear }}"
                                                style="font-size: 20px" name="namear"
                                                >


                                        </div>
                                        <div class="form-group">
                                            <label style="font-size: 20px"> اسم القرية - إنجليزي </label>
                                            <input type="text" class="form-control" value="{{ $village->nameen }}"
                                                style="font-size: 20px" name="nameen"
                                                >


                                        </div>
                                        <div class="form-group">
                                            <label style="font-size: 20px">الوصف - عربي</label>

                                            <textarea name="descar" rows="10" class="form-control no-resize"
                                                >{{ $village->descar }}</textarea>
                                        </div>
                                        <div class="form-group">
                                            <label style="font-size: 20px">الوصف- إنجليزي</label>

                                            <textarea name="descen" rows="10" class="form-control no-resize"
                                               >{{ $village->descen }}</textarea>
                                        </div>



                                        <div class="row clearfix">
                                            <div class="col-lg-12">
                                                <label style="font-size: 20px">الصورة</label>
                                                <input type="file" width="590px" height="390px" class="dropify"
                                                    data-default-file="{{ url('images/villages/' . $village->image) }}"
                                                    name="image">
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label style="font-size: 20px">الحالة</label>
                                            <div class="custom-control custom-switch">
                                                <input type="checkbox" class="custom-control-input" name="status"
                                                    id="status" @if ($village->status == 'Visible')
                                                checked @endif>
                                                <label class="custom-control-label" style="font-size: 20px"
                                                    for="status">التفعيل</label>

                                            </div>
                                        </div>




                                    </div>
                                </div>
                                <div>
                                    <button style="font-size: 20px" class="btn btn-sm btn-primary" type="submit">
                                       تعديل
                                    </button>


                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>

    </script>

@endsection

resources/views/cms/admin/villages/index.blade.php
@extends('cms.admin.parent')
@section('content')

    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ route('admin.dashbord') }}"
                                        style="font-size: 20px">الرئيسية</a></li>
                                <li class="breadcrumb-item"><a href="{{ route('village.create') }}"
                                        style="font-size: 20px">قرية جديدة</a></li>
                                <li class="breadcrumb-item " style="font-size: 20px" aria-current="page">
                                    القرى والبلدات
                                </li>
                            </ol>
                        </nav>
                    </div>

                </div>
            </div>

            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="header">
                            <h2 style="font-size: 20px">القرى والبلدات</h2>

                        </div>
                        <div class="table-responsive">
                            <table class="table table-hover js-basic-example dataTable table-custom spacing5 mb-0">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th style="font-size: 17px">صورة القرية</th>
                                        <th style="font-size: 17px"> اسم القرية</th>
                                        <th style="font-size: 17px">الوصف  </th>
                                        <th style="font-size: 17px">عرض </th>
                                        <th style="font-size: 17px">حالة العرض</th>
                                        <th style="font-size: 17px">تاريخ الإنشاء</th>
                                        <th style="font-size: 17px">الإعدادات</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <span hidden>{{ $i = 0 }}</span>
                                    @foreach ($villages as $item)
                                        <span hidden>{{ $i++ }}</span>

                                        <tr>
                                            <td>{{ $i }}</td>
                                            <td class="w60">
                                                <img src="{{ url('images/villages/' . $item->image) }}"
                                                    data-toggle="tooltip" data-placement="top" title="{{ $item->title }}"
                                                    alt="Avatar" class="w35 h35 rounded">
                                            </td>



                                                <td><span style="font-size: 17px">{{ $item->namear }}</span></td>
                                                <td><span style="font-size: 17px">{{ Str::limit($item->descar, 10) }}</span></td>


                                            <td>
                                                <a class="btn btn-info btn-sm"
                                                    href="{{ route('village.show',$item->id) }}">
                                                    <i class="icon-note">
                                                    </i>
                                                    مشاهدة
                                                </a>
                                                <span class="badge badge-dark"></span>
                                            </td>
                                            <td>
                                                @if ($item->status == 'Visible')
                                                    <span style="font-size: 17px"
                                                        class="badge badge-success">مُفعلة</span>
                                                @else
                                                    <span style="font-size: 17px"
                                                        class="badge badge-danger">مُطفئة</span>
                                                @endif

                                            </td>
                                            <td><span
                                                    style="font-size: 17px">{{ $item->created_at->format('Y.m.d') }}</span>
                                            </td>

                                            <td>
                                                <a href="{{ route('village.edit',$item->id) }}"
                                                    type="button" style="font-size: 20px" class="btn btn-sm btn-default"
                                                    title="تعديل"><i class="fa fa-edit"></i>
                                                    تعديل</a>
                                                <a onclick="confirmDelete(this, '{{ $item->id }}')" type="button"
                                                    style="font-size: 20px" class="btn btn-sm btn-default js-sweetalert"
                                                    title=" حذف" data-type="confirm"><i
                                                        class="fa fa-trash-o text-danger">
                                                     حذف </i></a>


                                            </td>




                                            {{-- <td>
                                                <a href="javascript:void(0);" class="btn btn-info btn-round">Interview</a>

                                            </td> --}}
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

@endsection
@section('script')
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script>
        function confirmDelete(app, id) {

            Swal.fire({
                title: 'هل انت متأكد من الحذف ؟',
                text: "لن تكون قادرا على استرجاعها",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'حذف',
                cancelButtonText: 'تراجع'
            }).then((result) => {
                if (result.value) {
                    deletecategory(app, id, )
                }
            })
        }

        function deletecategory(app, id) {
            axios.delete('/cms/admin/village/' + id)
                .then(function(response) {
                    // handle success (Status Code: 200)
                    console.log(response);
                    console.log(response.data);
                    showMessage(response.data);
                    app.closest('tr').remove();
                })
                .catch(function(error) {
                    // handle error (Status Code: 400)
                    console.log(error);
                    console.log(error.response.data);
                    showMessage(error.response.data);
                })
                .then(function() {
                    // always executed
                });
        }

        function showMessage(data) {
            Swal.fire({
                position: 'center',
                icon: data.icon,
                title: data.title,
                showConfirmButton: false,
                timer: 1500
            })
        }

    </script>

@endsection