routes/web.php
<?php

use App\Http\Controllers\AreaController;
use App\Http\Controllers\Auth\SuperAuthController;
use App\Http\Controllers\BreifController;
use App\Http\Controllers\BridController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CenterController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\DashbordController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\SuperController;
use App\Http\Controllers\VillageController;
use App\Http\Controllers\VisionController;
use App\Models\Area;
use App\Models\Super;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('cms/admin')->middleware('auth:super')->group(function () {

        Route::resource('vision', VisionController::class);
        Route::resource('village', VillageController::class)->middleware('auth:super');
        Route::resource('category',CategoryController::class)->middleware('auth:super');
        Route::resource('message',MessageController::class)->middleware('auth:super');
        Route::resource('breif',BreifController::class)->middleware('auth:super');
        Route::resource('area',AreaController::class)->middleware('auth:super');
        Route::resource('brid',BridController::class)->middleware('auth:super');
        Route::resource('super',SuperController::class)->middleware('auth:super');

        Route::resource('center',CenterController::class)->middleware('auth:super')->middleware('auth:super');
        Route::get('/',[DashbordController::class,'admin'])->name('admin.dashbord')->middleware('auth:super');
        Route::get('logout', [SuperAuthController::class,'logout'])->name('super.logout')->middleware('auth:super');

});

Route::prefix('cms/admin/')->namespace('Auth')->group(function () {

    Route::get('page/login', [SuperAuthController::class,'showLoginView'])->name('super.login.view');
    Route::post('login',  [SuperAuthController::class,'login'])->name('super.login.store');
    Route::get('blocked', [SuperAuthController::class,'blocked'])->name('super.blocked');

    // Route::get('forgot-password', 'AdminAuthController@showForgetPassword')->name('cms.admin.forgot_password_view');
    // Route::post('forgot-password', 'AdminAuthController@requestNewPassword')->name('cms.admin.forgot_password');
});

Route::get('/test', function () {
    App::setLocale('en');
    dd(App::getLocale());
});

app/Models/Brid.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brid extends Model
{
    use HasFactory;
}

app/Http/Controllers/BridController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateBrid;
use App\Models\Brid;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;

class BridController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('cms.admin.brids.index',['brid'=>Brid::first()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateBrid $request)
    {

        $brid=Brid::first();
        if(!$brid){
            $brid=new Brid();
        }
        $brid->descar=$request->get('descar');
        $brid->descen=$request->get('descen');
        $brid->titlear=$request->get('titlear');
        $brid->titleen->$request->get('titleen');
        $brid->countplant=$request->get('countplant');
        $brid->countmammal=$request->get('countmammal');
        $brid->countbrid=$request->get('countbrid');
        $save=$brid->save();
       if ($save) {
           $lang = App::getLocale();
            if ($lang == 'ar') {
                SuccessError::Success('تم التعديل بنجاح');
                return redirect()->back();
            } else {
                SuccessError::Success('Edit successfully');
                return redirect()->back();

        }

        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Brid  $brid
     * @return \Illuminate\Http\Response
     */
    public function show(Brid $brid)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Brid  $brid
     * @return \Illuminate\Http\Response
     */
    public function edit(Brid $brid)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Brid  $brid
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Brid $brid)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Brid  $brid
     * @return \Illuminate\Http\Response
     */
    public function destroy(Brid $brid)
    {
        //
    }
}

resources/views/cms/admin/brids/index.blade.php
@extends('cms.admin.parent')
@section('content')



    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row clearfix">
                    <div class="col-md-6 col-sm-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ route('admin.dashbord') }}"
                                        style="font-size: 20px">الرئيسية</a></li>
                                {{-- <li class="breadcrumb-item"><a
                                        href="{{ route('center.index', app()->getLocale()) }}"
                                        style="font-size: 20px">{{ __('parent.center') }}</a></li>
                                --}}
                                <li class="breadcrumb-item active" aria-current="page" style="font-size: 20px">
                                    التنوع الحيوي
                                </li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right hidden-xs">
                        {{-- <a
                            href="https://themeforest.net/item/oculux-bootstrap-4x-admin-dashboard-clean-modern-ui-kit/23091507"
                            class="btn btn-sm btn-success" title="Themeforest"><i class="icon-basket"></i> Buy Now</a>
                        --}}
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="body">
                            <form method="POST" action="{{ route('brid.store') }}"
                                enctype="multipart/form-data">


                                @if ($errors->any())
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                    </div>
                                @endif
                                @if (session()->has('message'))
                                    <div class="alert {{ session()->get('status') }} alert-dismissible fade show"
                                        role="alert">
                                        <span> {{ session()->get('message') }}</span>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endif
                                @csrf
                                <div class="form-group row">
                                    <div class="col-md-12 col-sm-10">
                                        {{-- الرؤية بالإنجليزية
                                        --}}
                                        <div class="form-group">
                                            <label style="font-size: 20px"> المحتوى - عربي</label>

                                            <textarea name="descar" rows="4" class="form-control no-resize"
                                                >@if ($brid){{ $brid->descar }} @endif </textarea>
                                        </div>
                                        <div class="form-group">
                                            <label style="font-size: 20px">المحتوى -إنجليزي</label>

                                            <textarea name="descen" rows="4" class="form-control no-resize"
                                              >@if ($brid){{ $brid->descen }}@endif</textarea>
                                        </div>
                                         <div class="form-group">
                                            <label style="font-size: 20px">عدد الفصائل النباتية</label>
                                            <input type="number" class="form-control" @if($brid) value={{ $brid->countplant }}@endif
                                                style="font-size: 20px" name="countplant"
                                                >
                                        </div>
                                          <div class="form-group">
                                            <label style="font-size: 20px">عدد فصائل الطيور</label>
                                            <input type="number" class="form-control" @if($brid) value={{ $brid->countbrid }}@endif
                                                style="font-size: 20px" name="countbrid"
                                                >
                                        </div>
                                           <div class="form-group">
                                            <label style="font-size: 20px">عدد فصائل الثديات</label>
                                            <input type="number" class="form-control" @if($brid) value={{ $brid->countmammal }}@endif
                                                style="font-size: 20px" name="countmammal"
                                                >
                                        </div>

                                        {{-- الرسلة بالإنجليزية
                                        --}}







                                    </div>
                                </div>
                                <div>
                                    <button style="font-size: 20px" class="btn btn-sm btn-primary" type="submit">
                                        حفظ
                                    </button>


                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script>

    </script>

@endsection